
/////////////////////////////// atob
 var _PADCHAR = "=",
  _ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

var _getbyte64 = function( s, i ) {
  var idx = _ALPHA.indexOf( s.charAt( i ) );

  if ( idx === -1 ) {
    throw "Cannot decode base64";
  }

  return idx;
}

var atob = function( s ) {
  var pads = 0,
    i,
    b10,
    imax = s.length,
    x = [];

  s = String( s );

  if ( imax === 0 ) {
    return s;
  }

  if ( imax % 4 !== 0 ) {
    throw "Cannot decode base64";
  }

  if ( s.charAt( imax - 1 ) === _PADCHAR ) {
    pads = 1;

    if ( s.charAt( imax - 2 ) === _PADCHAR ) {
      pads = 2;
    }

    // either way, we want to ignore this last block
    imax -= 4;
  }

  for ( i = 0; i < imax; i += 4 ) {
    b10 = ( _getbyte64( s, i ) << 18 ) | ( _getbyte64( s, i + 1 ) << 12 ) | ( _getbyte64( s, i + 2 ) << 6 ) | _getbyte64( s, i + 3 );
    x.push( String.fromCharCode( b10 >> 16, ( b10 >> 8 ) & 0xff, b10 & 0xff ) );
  }

  switch ( pads ) {
    case 1:
      b10 = ( _getbyte64( s, i ) << 18 ) | ( _getbyte64( s, i + 1 ) << 12 ) | ( _getbyte64( s, i + 2 ) << 6 );
      x.push( String.fromCharCode( b10 >> 16, ( b10 >> 8 ) & 0xff ) );
      break;

    case 2:
      b10 = ( _getbyte64( s, i ) << 18) | ( _getbyte64( s, i + 1 ) << 12 );
      x.push( String.fromCharCode( b10 >> 16 ) );
      break;
  }

  return x.join( "" );
}

var _getbyte = function ( s, i ) {
  var x = s.charCodeAt( i );

  if ( x > 255 ) {
    throw "INVALID_CHARACTER_ERR: DOM Exception 5";
  }

  return x;
}

var btoa = function ( s ) {
  if ( arguments.length !== 1 ) {
    throw "SyntaxError: exactly one argument required";
  }

  s = String( s );

  var i,
    b10,
    x = [],
    imax = s.length - s.length % 3;

  if ( s.length === 0 ) {
    return s;
  }

  for ( i = 0; i < imax; i += 3 ) {
    b10 = ( _getbyte( s, i ) << 16 ) | ( _getbyte( s, i + 1 ) << 8 ) | _getbyte( s, i + 2 );
    x.push( _ALPHA.charAt( b10 >> 18 ) );
    x.push( _ALPHA.charAt( ( b10 >> 12 ) & 0x3F ) );
    x.push( _ALPHA.charAt( ( b10 >> 6 ) & 0x3f ) );
    x.push( _ALPHA.charAt( b10 & 0x3f ) );
  }

  switch ( s.length - imax ) {
    case 1:
      b10 = _getbyte( s, i ) << 16;
      x.push( _ALPHA.charAt( b10 >> 18 ) + _ALPHA.charAt( ( b10 >> 12 ) & 0x3F ) + _PADCHAR + _PADCHAR );
      break;

    case 2:
      b10 = ( _getbyte( s, i ) << 16 ) | ( _getbyte( s, i + 1 ) << 8 );
      x.push( _ALPHA.charAt( b10 >> 18 ) + _ALPHA.charAt( ( b10 >> 12 ) & 0x3F ) + _ALPHA.charAt( ( b10 >> 6 ) & 0x3f ) + _PADCHAR );
      break;
  }

  return x.join( "" );
}
///////////////////////////// atob

var subjectJsonB64 = "ewogICJjb250cmFjdF9uYW1lIjogIlN1YmplY3QiLAogICJhYmkiOiBbCiAgICB7CiAgICAgICJjb25zdGFudCI6IGZhbHNlLAogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9vd25lciIsCiAgICAgICAgICAidHlwZSI6ICJhZGRyZXNzIgogICAgICAgIH0KICAgICAgXSwKICAgICAgIm5hbWUiOiAic2V0T3duZXIiLAogICAgICAib3V0cHV0cyI6IFtdLAogICAgICAicGF5YWJsZSI6IGZhbHNlLAogICAgICAidHlwZSI6ICJmdW5jdGlvbiIKICAgIH0sCiAgICB7CiAgICAgICJjb25zdGFudCI6IHRydWUsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX0lEIiwKICAgICAgICAgICJ0eXBlIjogInVpbnQyNTYiCiAgICAgICAgfQogICAgICBdLAogICAgICAibmFtZSI6ICJnZXRDZXJ0aWZpY2F0ZSIsCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9jZXJ0aWZpY2F0ZSIsCiAgICAgICAgICAidHlwZSI6ICJhZGRyZXNzIgogICAgICAgIH0KICAgICAgXSwKICAgICAgInBheWFibGUiOiBmYWxzZSwKICAgICAgInR5cGUiOiAiZnVuY3Rpb24iCiAgICB9LAogICAgewogICAgICAiY29uc3RhbnQiOiBmYWxzZSwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJjZXJ0aWZpY2F0ZSIsCiAgICAgICAgICAidHlwZSI6ICJhZGRyZXNzIgogICAgICAgIH0KICAgICAgXSwKICAgICAgIm5hbWUiOiAiYWRkQ2VydGlmaWNhdGUiLAogICAgICAib3V0cHV0cyI6IFtdLAogICAgICAicGF5YWJsZSI6IGZhbHNlLAogICAgICAidHlwZSI6ICJmdW5jdGlvbiIKICAgIH0sCiAgICB7CiAgICAgICJjb25zdGFudCI6IHRydWUsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm5hbWUiOiAiZ2V0T3duZXIiLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfb3duZXIiLAogICAgICAgICAgInR5cGUiOiAiYWRkcmVzcyIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJwYXlhYmxlIjogZmFsc2UsCiAgICAgICJ0eXBlIjogImZ1bmN0aW9uIgogICAgfSwKICAgIHsKICAgICAgImNvbnN0YW50IjogdHJ1ZSwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAibmFtZSI6ICJnZXRQcm9wcyIsCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9JRCIsCiAgICAgICAgICAidHlwZSI6ICJ1aW50MjU2IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX2JpcnRoZGF0ZSIsCiAgICAgICAgICAidHlwZSI6ICJ1aW50MjU2IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX2Z1bGxuYW1lIiwKICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9nZW5kZXIiLAogICAgICAgICAgInR5cGUiOiAidWludDgiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfb3JpZ2luIiwKICAgICAgICAgICJ0eXBlIjogInVpbnQ4IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX2NlcnRpZmljYXRlcyIsCiAgICAgICAgICAidHlwZSI6ICJ1aW50MjU2IgogICAgICAgIH0KICAgICAgXSwKICAgICAgInBheWFibGUiOiBmYWxzZSwKICAgICAgInR5cGUiOiAiZnVuY3Rpb24iCiAgICB9LAogICAgewogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9JRCIsCiAgICAgICAgICAidHlwZSI6ICJ1aW50MjU2IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX2JpcnRoZGF0ZSIsCiAgICAgICAgICAidHlwZSI6ICJ1aW50MjU2IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX2Z1bGxuYW1lIiwKICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9nZW5kZXIiLAogICAgICAgICAgInR5cGUiOiAidWludDgiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfb3JpZ2luIiwKICAgICAgICAgICJ0eXBlIjogInVpbnQ4IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiY2VydGlmaWNhdGUiLAogICAgICAgICAgInR5cGUiOiAiYWRkcmVzcyIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJwYXlhYmxlIjogZmFsc2UsCiAgICAgICJ0eXBlIjogImNvbnN0cnVjdG9yIgogICAgfQogIF0sCiAgInVubGlua2VkX2JpbmFyeSI6ICIweDYwNjA2MDQwNTIzNDE1NjEwMDBmNTc2MDAwODBmZDViNjA0MDUxNjEwNTdjMzgwMzgwNjEwNTdjODMzOTgxMDE2MDQwNTI4MDgwNTE5MTkwNjAyMDAxODA1MTkxOTA2MDIwMDE4MDUxODIwMTkxOTA2MDIwMDE4MDUxOTE5MDYwMjAwMTgwNTE5MTkwNjAyMDAxODA1MTkxNTA1MDViNWI2MDAwODA1NDYwMDE2MGEwNjAwMjBhMDMxOTE2MzM2MDAxNjBhMDYwMDIwYTAzMTYxNzkwNTU1YjYwMDE4NjkwNTU2MDAyODU5MDU1NjAwMzg0ODA1MTYxMDA4ODkyOTE2MDIwMDE5MDYxMDExZjU2NWI1MDYwMDQ4MDU0NjBmZjg0ODExNjYxMDEwMDAyNjFmZjAwMTk5MTg3MTY2MGZmMTk5MDkzMTY5MjkwOTIxNzE2MTc5MDU1NjEwMGMxODE2NDAxMDAwMDAwMDA2MTAyMjc2MTAwY2Q4MjAyMTcwNDU2NWI1YjUwNTA1MDUwNTA1MDYxMDFiZjU2NWI2MDAwNTQzMzYwMDE2MGEwNjAwMjBhMDM5MDgxMTY5MTE2MTQ2MTAwZTg1NzYwMDA4MGZkNWI2MDA1ODA1NDYwMDA5MDgxNTI2MDA2NjAyMDUyNjA0MDkwMjA4MDU0NjAwMTYwYTA2MDAyMGEwMzE5MTY2MDAxNjBhMDYwMDIwYTAzODQxNjE3OTA1NTgwNTQ2MDAxMDE5MDU1NWI1YjUwNTY1YjgyODA1NDYwMDE4MTYwMDExNjE1NjEwMTAwMDIwMzE2NjAwMjkwMDQ5MDYwMDA1MjYwMjA2MDAwMjA5MDYwMWYwMTYwMjA5MDA0ODEwMTkyODI2MDFmMTA2MTAxNjA1NzgwNTE2MGZmMTkxNjgzODAwMTE3ODU1NTYxMDE4ZDU2NWI4MjgwMDE2MDAxMDE4NTU1ODIxNTYxMDE4ZDU3OTE4MjAxNWI4MjgxMTExNTYxMDE4ZDU3ODI1MTgyNTU5MTYwMjAwMTkxOTA2MDAxMDE5MDYxMDE3MjU2NWI1YjUwNjEwMTlhOTI5MTUwNjEwMTllNTY1YjUwOTA1NjViNjEwMWJjOTE5MDViODA4MjExMTU2MTAxOWE1NzYwMDA4MTU1NjAwMTAxNjEwMWE0NTY1YjUwOTA1NjViOTA1NjViNjEwM2FlODA2MTAxY2U2MDAwMzk2MDAwZjMwMDYwNjA2MDQwNTI2M2ZmZmZmZmZmN2MwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjAwMDM1MDQxNjYzMTNhZjQwMzU4MTE0NjEwMDY5NTc4MDYzNTE2NDBmZWUxNDYxMDA4YTU3ODA2MzdjNmViZGU5MTQ2MTAwYmM1NzgwNjM4OTNkMjBlODE0NjEwMGRkNTc4MDYzZWMxODkzYjQxNDYxMDEwYzU3NWI2MDAwODBmZDViMzQxNTYxMDA3NDU3NjAwMDgwZmQ1YjYxMDA4ODYwMDE2MGEwNjAwMjBhMDM2MDA0MzUxNjYxMDFjMTU2NWIwMDViMzQxNTYxMDA5NTU3NjAwMDgwZmQ1YjYxMDBhMDYwMDQzNTYxMDIwOTU2NWI2MDQwNTE2MDAxNjBhMDYwMDIwYTAzOTA5MTE2ODE1MjYwMjAwMTYwNDA1MTgwOTEwMzkwZjM1YjM0MTU2MTAwYzc1NzYwMDA4MGZkNWI2MTAwODg2MDAxNjBhMDYwMDIwYTAzNjAwNDM1MTY2MTAyMjc1NjViMDA1YjM0MTU2MTAwZTg1NzYwMDA4MGZkNWI2MTAwYTA2MTAyODY1NjViNjA0MDUxNjAwMTYwYTA2MDAyMGEwMzkwOTExNjgxNTI2MDIwMDE2MDQwNTE4MDkxMDM5MGYzNWIzNDE1NjEwMTE3NTc2MDAwODBmZDViNjEwMTFmNjEwMjk2NTY1YjYwNDA1MTg2ODE1MjYwMjA4MTAxODY5MDUyNjBmZjgwODUxNjYwNjA4MzAxNTI4MzE2NjA4MDgyMDE1MjYwYTA4MTAxODI5MDUyNjBjMDYwNDA4MjAxODE4MTUyOTA4MjAxODY4MTgxNTE4MTUyNjAyMDAxOTE1MDgwNTE5MDYwMjAwMTkwODA4MzgzNjAwMDViODM4MTEwMTU2MTAxODE1NzgwODIwMTUxODE4NDAxNTI1YjYwMjAwMTYxMDE2ODU2NWI1MDUwNTA1MDkwNTA5MDgxMDE5MDYwMWYxNjgwMTU2MTAxYWU1NzgwODIwMzgwNTE2MDAxODM2MDIwMDM2MTAxMDAwYTAzMTkxNjgxNTI2MDIwMDE5MTUwNWI1MDk3NTA1MDUwNTA1MDUwNTA1MDYwNDA1MTgwOTEwMzkwZjM1YjYwMDA1NDMzNjAwMTYwYTA2MDAyMGEwMzkwODExNjkxMTYxNDYxMDFkYzU3NjAwMDgwZmQ1YjYwMDA4MDU0NzNmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmMTkxNjYwMDE2MGEwNjAwMjBhMDM4MzE2MTc5MDU1NWI1YjUwNTY1YjYwMDA4MTgxNTI2MDA2NjAyMDUyNjA0MDkwMjA1NDYwMDE2MGEwNjAwMjBhMDMxNjViOTE5MDUwNTY1YjYwMDA1NDMzNjAwMTYwYTA2MDAyMGEwMzkwODExNjkxMTYxNDYxMDI0MjU3NjAwMDgwZmQ1YjYwMDU4MDU0NjAwMDkwODE1MjYwMDY2MDIwNTI2MDQwOTAyMDgwNTQ3M2ZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmYxOTE2NjAwMTYwYTA2MDAyMGEwMzg0MTYxNzkwNTU4MDU0NjAwMTAxOTA1NTViNWI1MDU2NWI2MDAwNTQ2MDAxNjBhMDYwMDIwYTAzMTY1YjkwNTY1YjYwMDA4MDYxMDJhMTYxMDM3MDU2NWI2MDAwODA2MDAwNjAwMTU0OTU1MDYwMDI1NDk0NTA2MDAzODA1NDYwMDE4MTYwMDExNjE1NjEwMTAwMDIwMzE2NjAwMjkwMDQ4MDYwMWYwMTYwMjA4MDkxMDQwMjYwMjAwMTYwNDA1MTkwODEwMTYwNDA1MjgwOTI5MTkwODE4MTUyNjAyMDAxODI4MDU0NjAwMTgxNjAwMTE2MTU2MTAxMDAwMjAzMTY2MDAyOTAwNDgwMTU2MTAzNDY1NzgwNjAxZjEwNjEwMzFiNTc2MTAxMDA4MDgzNTQwNDAyODM1MjkxNjAyMDAxOTE2MTAzNDY1NjViODIwMTkxOTA2MDAwNTI2MDIwNjAwMDIwOTA1YjgxNTQ4MTUyOTA2MDAxMDE5MDYwMjAwMTgwODMxMTYxMDMyOTU3ODI5MDAzNjAxZjE2ODIwMTkxNWI1MDUwNjAwNDU0NjAwNTU0OTQ5ODUwNjBmZjgwODIxNjk4NTA2MTAxMDA5MDkxMDQxNjk1NTA5MjkzNTA1MDUwNTA1YjkwOTE5MjkzOTQ5NTU2NWI2MDIwNjA0MDUxOTA4MTAxNjA0MDUyNjAwMDgxNTI5MDU2MDBhMTY1NjI3YTdhNzIzMDU4MjA5MzcwOWI0ZTM1NTI1NjhlNTNhNWFmYjRhMWJjYzc4MGRlMzZlNTIxYzYyZDk2ZTZjNDhiNzE2Y2FlNTIwZmQwMDAyOSIsCiAgIm5ldHdvcmtzIjogewogICAgIjEiOiB7CiAgICAgICJldmVudHMiOiB7fSwKICAgICAgImxpbmtzIjoge30sCiAgICAgICJhZGRyZXNzIjogIjB4ZGVjNmMwY2U0MDY0M2U4MDJiNDUyNjg3Mzc4M2FlMjVhZDI2ZGQ5NCIsCiAgICAgICJ1cGRhdGVkX2F0IjogMTUxMzcwMDE1MzEyOAogICAgfQogIH0sCiAgInNjaGVtYV92ZXJzaW9uIjogIjAuMC41IiwKICAidXBkYXRlZF9hdCI6IDE1MTM3MDAxNTMxMjgKfQ==";

try {
  var subjectJson = atob(subjectJsonB64);
  var subjectProto = JSON.parse(subjectJson);
  var subjectProxy = web3.eth.contract(subjectProto.abi);

  var contract = subjectProxy.at($$$address$$$);
  var props = contract.getProps();
  var subject = {};
  subject.ID = new Number(props[0]);
  subject.birthdate = new Number(props[1]);
  subject.name = props[2];
  subject.gender = new Number(props[3]);
  subject.origin = new Number(props[4]);
  subject.certificates = [];
  var numCerts = new Number(props[5]);
  for(var i = 0; i < numCerts; i++) {
    subject.certificates.push(contract.getCertificate(i));
  }
  console.log(JSON.stringify(subject));
}
catch(e) {
  console.log("EXCEPTION:");
  console.log(e);
};
