
/////////////////////////////// atob
 var _PADCHAR = "=",
  _ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

var _getbyte64 = function( s, i ) {
  var idx = _ALPHA.indexOf( s.charAt( i ) );

  if ( idx === -1 ) {
    throw "Cannot decode base64";
  }

  return idx;
}

var atob = function( s ) {
  var pads = 0,
    i,
    b10,
    imax = s.length,
    x = [];

  s = String( s );

  if ( imax === 0 ) {
    return s;
  }

  if ( imax % 4 !== 0 ) {
    throw "Cannot decode base64";
  }

  if ( s.charAt( imax - 1 ) === _PADCHAR ) {
    pads = 1;

    if ( s.charAt( imax - 2 ) === _PADCHAR ) {
      pads = 2;
    }

    // either way, we want to ignore this last block
    imax -= 4;
  }

  for ( i = 0; i < imax; i += 4 ) {
    b10 = ( _getbyte64( s, i ) << 18 ) | ( _getbyte64( s, i + 1 ) << 12 ) | ( _getbyte64( s, i + 2 ) << 6 ) | _getbyte64( s, i + 3 );
    x.push( String.fromCharCode( b10 >> 16, ( b10 >> 8 ) & 0xff, b10 & 0xff ) );
  }

  switch ( pads ) {
    case 1:
      b10 = ( _getbyte64( s, i ) << 18 ) | ( _getbyte64( s, i + 1 ) << 12 ) | ( _getbyte64( s, i + 2 ) << 6 );
      x.push( String.fromCharCode( b10 >> 16, ( b10 >> 8 ) & 0xff ) );
      break;

    case 2:
      b10 = ( _getbyte64( s, i ) << 18) | ( _getbyte64( s, i + 1 ) << 12 );
      x.push( String.fromCharCode( b10 >> 16 ) );
      break;
  }

  return x.join( "" );
}

var _getbyte = function ( s, i ) {
  var x = s.charCodeAt( i );

  if ( x > 255 ) {
    throw "INVALID_CHARACTER_ERR: DOM Exception 5";
  }

  return x;
}

var btoa = function ( s ) {
  if ( arguments.length !== 1 ) {
    throw "SyntaxError: exactly one argument required";
  }

  s = String( s );

  var i,
    b10,
    x = [],
    imax = s.length - s.length % 3;

  if ( s.length === 0 ) {
    return s;
  }

  for ( i = 0; i < imax; i += 3 ) {
    b10 = ( _getbyte( s, i ) << 16 ) | ( _getbyte( s, i + 1 ) << 8 ) | _getbyte( s, i + 2 );
    x.push( _ALPHA.charAt( b10 >> 18 ) );
    x.push( _ALPHA.charAt( ( b10 >> 12 ) & 0x3F ) );
    x.push( _ALPHA.charAt( ( b10 >> 6 ) & 0x3f ) );
    x.push( _ALPHA.charAt( b10 & 0x3f ) );
  }

  switch ( s.length - imax ) {
    case 1:
      b10 = _getbyte( s, i ) << 16;
      x.push( _ALPHA.charAt( b10 >> 18 ) + _ALPHA.charAt( ( b10 >> 12 ) & 0x3F ) + _PADCHAR + _PADCHAR );
      break;

    case 2:
      b10 = ( _getbyte( s, i ) << 16 ) | ( _getbyte( s, i + 1 ) << 8 );
      x.push( _ALPHA.charAt( b10 >> 18 ) + _ALPHA.charAt( ( b10 >> 12 ) & 0x3F ) + _ALPHA.charAt( ( b10 >> 6 ) & 0x3f ) + _PADCHAR );
      break;
  }

  return x.join( "" );
}
///////////////////////////// atob

var certificateJsonB64 = "ewogICJjb250cmFjdF9uYW1lIjogIkNlcnRpZmljYXRlIiwKICAiYWJpIjogWwogICAgewogICAgICAiY29uc3RhbnQiOiB0cnVlLAogICAgICAiaW5wdXRzIjogW10sCiAgICAgICJuYW1lIjogImdldENlcnRpZmljYXRlIiwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX3R5cGVfaWQiLAogICAgICAgICAgInR5cGUiOiAidWludDgiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfZHRfY3JlYXRlIiwKICAgICAgICAgICJ0eXBlIjogInVpbnQyNTYiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfc3ViamVjdHNfY291bnQiLAogICAgICAgICAgInR5cGUiOiAidWludDI1NiIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJwYXlhYmxlIjogZmFsc2UsCiAgICAgICJ0eXBlIjogImZ1bmN0aW9uIgogICAgfSwKICAgIHsKICAgICAgImNvbnN0YW50IjogZmFsc2UsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX2lkIiwKICAgICAgICAgICJ0eXBlIjogInVpbnQyNTYiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfdmFsaWRhdGVfaGFzaCIsCiAgICAgICAgICAidHlwZSI6ICJ1aW50MjU2IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX2JpcnRoZGF5IiwKICAgICAgICAgICJ0eXBlIjogInVpbnQyNTYiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfZ2VuZGVyIiwKICAgICAgICAgICJ0eXBlIjogInVpbnQ4IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX2R0X3NpZ24iLAogICAgICAgICAgInR5cGUiOiAidWludDI1NiIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9mdWxsbmFtZSIsCiAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgfQogICAgICBdLAogICAgICAibmFtZSI6ICJTaWduIiwKICAgICAgIm91dHB1dHMiOiBbXSwKICAgICAgInBheWFibGUiOiB0cnVlLAogICAgICAidHlwZSI6ICJmdW5jdGlvbiIKICAgIH0sCiAgICB7CiAgICAgICJjb25zdGFudCI6IHRydWUsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiaW5kZXgiLAogICAgICAgICAgInR5cGUiOiAidWludDI1NiIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJuYW1lIjogImdldFN1YmplY3QiLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfaWQiLAogICAgICAgICAgInR5cGUiOiAidWludDI1NiIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl92YWxpZGF0ZV9oYXNoIiwKICAgICAgICAgICJ0eXBlIjogInVpbnQyNTYiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfYmlydGhkYXkiLAogICAgICAgICAgInR5cGUiOiAidWludDI1NiIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9mdWxsbmFtZSIsCiAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfZ2VuZGVyIiwKICAgICAgICAgICJ0eXBlIjogInVpbnQ4IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiX2R0X3NpZ24iLAogICAgICAgICAgInR5cGUiOiAidWludDI1NiIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9kdF9jYW5jZWwiLAogICAgICAgICAgInR5cGUiOiAidWludDI1NiIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJwYXlhYmxlIjogZmFsc2UsCiAgICAgICJ0eXBlIjogImZ1bmN0aW9uIgogICAgfSwKICAgIHsKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJfdHlwZV9pZCIsCiAgICAgICAgICAidHlwZSI6ICJ1aW50OCIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9kdF9jcmVhdGUiLAogICAgICAgICAgInR5cGUiOiAidWludDI1NiIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIl9zdWJqZWN0c19hZGRyIiwKICAgICAgICAgICJ0eXBlIjogImFkZHJlc3NbXSIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJwYXlhYmxlIjogZmFsc2UsCiAgICAgICJ0eXBlIjogImNvbnN0cnVjdG9yIgogICAgfQogIF0sCiAgInVubGlua2VkX2JpbmFyeSI6ICIweDYwNjA2MDQwNTIzNDE1NjEwMDBmNTc2MDAwODBmZDViNjA0MDUxNjEwODdhMzgwMzgwNjEwODdhODMzOTgxMDE2MDQwNTI4MDgwNTE5MTkwNjAyMDAxODA1MTkxOTA2MDIwMDE4MDUxOTA5MTAxOTA1MDViNjAwMDgwNTQ2MGZmMTkxNjYwZmY4NTE2MTc5MDU1NjAwMTgyOTA1NTYwMDI4MTgwNTE2MTAwNjA5MjkxNjAyMDAxOTA2MTAwODU1NjViNTA2MDA0ODA1NDYwMDE2MGEwNjAwMjBhMDMxOTE2MzM2MDAxNjBhMDYwMDIwYTAzMTYxNzkwNTU1YjUwNTA1MDYxMDExODU2NWI4MjgwNTQ4MjgyNTU5MDYwMDA1MjYwMjA2MDAwMjA5MDgxMDE5MjgyMTU2MTAwZGM1NzkxNjAyMDAyODIwMTViODI4MTExMTU2MTAwZGM1NzgyNTE4MjU0NjAwMTYwYTA2MDAyMGEwMzE5MTY2MDAxNjBhMDYwMDIwYTAzOTE5MDkxMTYxNzgyNTU2MDIwOTI5MDkyMDE5MTYwMDE5MDkxMDE5MDYxMDBhNTU2NWI1YjUwNjEwMGU5OTI5MTUwNjEwMGVkNTY1YjUwOTA1NjViNjEwMTE1OTE5MDViODA4MjExMTU2MTAwZTk1NzgwNTQ2MDAxNjBhMDYwMDIwYTAzMTkxNjgxNTU2MDAxMDE2MTAwZjM1NjViNTA5MDU2NWI5MDU2NWI2MTA3NTM4MDYxMDEyNzYwMDAzOTYwMDBmMzAwNjA2MDYwNDA1MjYzZmZmZmZmZmY3YzAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA2MDAwMzUwNDE2NjNhZTE1ZWI4ZTgxMTQ2MTAwNTM1NzgwNjNjNWU3ZGEyMzE0NjEwMDkwNTc4MDYzZjZkZDAxODcxNDYxMDBmMTU3NWI2MDAwODBmZDViMzQxNTYxMDA1ZTU3NjAwMDgwZmQ1YjYxMDA2NjYxMDFiMDU2NWI2MDQwNTE4MDg0NjBmZjE2NjBmZjE2ODE1MjYwMjAwMTgzODE1MjYwMjAwMTgyODE1MjYwMjAwMTkzNTA1MDUwNTA2MDQwNTE4MDkxMDM5MGYzNWI2MTAwZWY2MDA0ODAzNTkwNjAyNDgwMzU5MTYwNDQzNTkxNjBmZjYwNjQzNTE2OTE2MDg0MzU5MTYwYzQ5MDYwYTQzNTkwODEwMTkwODMwMTM1ODA2MDIwNjAxZjgyMDE4MTkwMDQ4MTAyMDE2MDQwNTE5MDgxMDE2MDQwNTI4MTgxNTI5MjkxOTA2MDIwODQwMTgzODM4MDgyODQzNzUwOTQ5NjUwNjEwMWM1OTU1MDUwNTA1MDUwNTA1NjViMDA1YjM0MTU2MTAwZmM1NzYwMDA4MGZkNWI2MTAxMDc2MDA0MzU2MTAzNTg1NjViNjA0MDUxODA4ODgxNTI2MDIwMDE4NzgxNTI2MDIwMDE4NjgxNTI2MDIwMDE4MDYwMjAwMTg1NjBmZjE2NjBmZjE2ODE1MjYwMjAwMTg0ODE1MjYwMjAwMTgzODE1MjYwMjAwMTgyODEwMzgyNTI4NjgxODE1MTgxNTI2MDIwMDE5MTUwODA1MTkwNjAyMDAxOTA4MDgzODM2MDAwNWI4MzgxMTAxNTYxMDE2ZjU3ODA4MjAxNTE4MTg0MDE1MjViNjAyMDAxNjEwMTU2NTY1YjUwNTA1MDUwOTA1MDkwODEwMTkwNjAxZjE2ODAxNTYxMDE5YzU3ODA4MjAzODA1MTYwMDE4MzYwMjAwMzYxMDEwMDBhMDMxOTE2ODE1MjYwMjAwMTkxNTA1YjUwOTg1MDUwNTA1MDUwNTA1MDUwNTA2MDQwNTE4MDkxMDM5MGYzNWI2MDAwNTQ2MDAxNTQ2MDAyNTQ2MGZmOTA5MjE2OTE1YjkwOTE5MjU2NWI2MDAwODA1YjYwMDI1NDgxMTAxNTYxMDIyYzU3NjAwMjgwNTQ4MjkwODExMDYxMDFlMTU3ZmU1YjkwNjAwMDUyNjAyMDYwMDAyMDkwMDE2MDAwNWI5MDU0OTA2MTAxMDAwYTkwMDQ2MDAxNjBhMDYwMDIwYTAzMTY2MDAxNjBhMDYwMDIwYTAzMTYzMzYwMDE2MGEwNjAwMjBhMDMxNjE0MTU2MTAyMjM1NzYwMDE5MTUwNjEwMjJjNTY1YjViNjAwMTAxNjEwMWM5NTY1YjYwMDE2MGEwNjAwMjBhMDMzMzE2NjAwMDkwODE1MjYwMDM2MDIwNTI2MDQwOTAyMDYwMDUwMTU0MTUxNTgwNjEwMjUzNTc1MDgxMTU1YjE1NjEwMjVkNTc2MDAwODBmZDViNjBlMDYwNDA1MTkwODEwMTYwNDA5MDgxNTI4OTgyNTI2MDIwODA4MzAxOGE5MDUyODE4MzAxODk5MDUyNjA2MDgzMDE4NjkwNTI2MGZmODgxNjYwODA4NDAxNTI2MGEwODMwMTg3OTA1MjYwMDA2MGMwODQwMTgxOTA1MjYwMDE2MGEwNjAwMjBhMDMzMzE2ODE1MjYwMDM5MDkxNTIyMDgxNTE4MTU1NjAyMDgyMDE1MTgxNjAwMTAxNTU2MDQwODIwMTUxODE2MDAyMDE1NTYwNjA4MjAxNTE4MTYwMDMwMTkwODA1MTYxMDJkZjkyOTE2MDIwMDE5MDYxMDY3NTU2NWI1MDYwODA4MjAxNTE2MDA0ODIwMTgwNTQ2MGZmMTkxNjYwZmY5MjkwOTIxNjkxOTA5MTE3OTA1NTYwYTA4MjAxNTE4MTYwMDUwMTU1NjBjMDgyMDE1MTYwMDY5MDkxMDE1NTUwMzQxNTYxMDM0YjU3NjAwNDU0NjAwMTYwYTA2MDAyMGEwMzE2MzQ4MDE1NjEwOGZjMDI5MDYwNDA1MTYwMDA2MDQwNTE4MDgzMDM4MTg1ODg4OGYxOTM1MDUwNTA1MDE1MTU2MTAzNGI1NzYwMDA4MGZkNWI1YjViNWI1MDUwNTA1MDUwNTA1MDUwNTY1YjYwMDA4MDYwMDA2MTAzNjU2MTA2ZjQ1NjViNjAwMDgwNjAwMDYwMDM2MDAwNjAwMjhhODE1NDgxMTAxNTE1NjEwMzdkNTdmZTViOTA2MDAwNTI2MDIwNjAwMDIwOTAwMTYwMDA1YjkwNTQ5MDYxMDEwMDBhOTAwNDYwMDE2MGEwNjAwMjBhMDMxNjYwMDE2MGEwNjAwMjBhMDMxNjYwMDE2MGEwNjAwMjBhMDMxNjgxNTI2MDIwMDE5MDgxNTI2MDIwMDE2MDAwMjA2MDAwMDE1NDk2NTA2MDAzNjAwMDYwMDI4YTgxNTQ4MTEwMTUxNTYxMDNkNjU3ZmU1YjkwNjAwMDUyNjAyMDYwMDAyMDkwMDE2MDAwNWI5MDU0OTA2MTAxMDAwYTkwMDQ2MDAxNjBhMDYwMDIwYTAzMTY2MDAxNjBhMDYwMDIwYTAzMTY2MDAxNjBhMDYwMDIwYTAzMTY4MTUyNjAyMDAxOTA4MTUyNjAyMDAxNjAwMDIwNjAwMTAxNTQ5NTUwNjAwMzYwMDA2MDAyOGE4MTU0ODExMDE1MTU2MTA0MmY1N2ZlNWI5MDYwMDA1MjYwMjA2MDAwMjA5MDAxNjAwMDViOTA1NDkwNjEwMTAwMGE5MDA0NjAwMTYwYTA2MDAyMGEwMzE2NjAwMTYwYTA2MDAyMGEwMzE2NjAwMTYwYTA2MDAyMGEwMzE2ODE1MjYwMjAwMTkwODE1MjYwMjAwMTYwMDAyMDYwMDIwMTU0OTQ1MDYwMDM2MDAwNjAwMjhhODE1NDgxMTAxNTE1NjEwNDg4NTdmZTViOTA2MDAwNTI2MDIwNjAwMDIwOTAwMTYwMDA1YjkwNTQ5MDYxMDEwMDBhOTAwNDYwMDE2MGEwNjAwMjBhMDMxNjYwMDE2MGEwNjAwMjBhMDMxNjYwMDE2MGEwNjAwMjBhMDMxNjgxNTI2MDIwMDE5MDgxNTI2MDIwMDE2MDAwMjA2MDAzMDE4MDU0NjAwMTgxNjAwMTE2MTU2MTAxMDAwMjAzMTY2MDAyOTAwNDgwNjAxZjAxNjAyMDgwOTEwNDAyNjAyMDAxNjA0MDUxOTA4MTAxNjA0MDUyODA5MjkxOTA4MTgxNTI2MDIwMDE4MjgwNTQ2MDAxODE2MDAxMTYxNTYxMDEwMDAyMDMxNjYwMDI5MDA0ODAxNTYxMDU1ZjU3ODA2MDFmMTA2MTA1MzQ1NzYxMDEwMDgwODM1NDA0MDI4MzUyOTE2MDIwMDE5MTYxMDU1ZjU2NWI4MjAxOTE5MDYwMDA1MjYwMjA2MDAwMjA5MDViODE1NDgxNTI5MDYwMDEwMTkwNjAyMDAxODA4MzExNjEwNTQyNTc4MjkwMDM2MDFmMTY4MjAxOTE1YjUwNTA1MDUwNTA5MzUwNjAwMzYwMDA2MDAyOGE4MTU0ODExMDE1MTU2MTA1Nzk1N2ZlNWI5MDYwMDA1MjYwMjA2MDAwMjA5MDAxNjAwMDViOTA1NDYwMDE2MGEwNjAwMjBhMDM2MTAxMDA5MjkwOTIwYTkwMDQxNjgxNTI2MDIwODEwMTkxOTA5MTUyNjA0MDAxNjAwMDkwODEyMDYwMDQwMTU0NjAwMjgwNTQ2MGZmOTA5MjE2OTU1MDYwMDM5MjkxOGI5MDgxMTA2MTA1Y2E1N2ZlNWI5MDYwMDA1MjYwMjA2MDAwMjA5MDAxNjAwMDViOTA1NDkwNjEwMTAwMGE5MDA0NjAwMTYwYTA2MDAyMGEwMzE2NjAwMTYwYTA2MDAyMGEwMzE2NjAwMTYwYTA2MDAyMGEwMzE2ODE1MjYwMjAwMTkwODE1MjYwMjAwMTYwMDAyMDYwMDUwMTU0OTE1MDYwMDM2MDAwNjAwMjhhODE1NDgxMTAxNTE1NjEwNjIzNTdmZTViOTA2MDAwNTI2MDIwNjAwMDIwOTAwMTYwMDA1YjkwNTQ5MDYxMDEwMDBhOTAwNDYwMDE2MGEwNjAwMjBhMDMxNjYwMDE2MGEwNjAwMjBhMDMxNjYwMDE2MGEwNjAwMjBhMDMxNjgxNTI2MDIwMDE5MDgxNTI2MDIwMDE2MDAwMjA2MDA2MDE1NDkwNTA1YjkxOTM5NTk3OTA5Mjk0OTY1MDU2NWI4MjgwNTQ2MDAxODE2MDAxMTYxNTYxMDEwMDAyMDMxNjYwMDI5MDA0OTA2MDAwNTI2MDIwNjAwMDIwOTA2MDFmMDE2MDIwOTAwNDgxMDE5MjgyNjAxZjEwNjEwNmI2NTc4MDUxNjBmZjE5MTY4MzgwMDExNzg1NTU2MTA2ZTM1NjViODI4MDAxNjAwMTAxODU1NTgyMTU2MTA2ZTM1NzkxODIwMTViODI4MTExMTU2MTA2ZTM1NzgyNTE4MjU1OTE2MDIwMDE5MTkwNjAwMTAxOTA2MTA2Yzg1NjViNWI1MDYxMDZmMDkyOTE1MDYxMDcwNjU2NWI1MDkwNTY1YjYwMjA2MDQwNTE5MDgxMDE2MDQwNTI2MDAwODE1MjkwNTY1YjYxMDcyNDkxOTA1YjgwODIxMTE1NjEwNmYwNTc2MDAwODE1NTYwMDEwMTYxMDcwYzU2NWI1MDkwNTY1YjkwNTYwMGExNjU2MjdhN2E3MjMwNTgyMGNkOGFlZDFlMGU0MzBhNjk0NTU2MjdiOGMwNDc0MDE3YTQ1ZWEzMzZiZDNkNzk5OTkxMTkwMjc3NjEyNzE5MmEwMDI5IiwKICAibmV0d29ya3MiOiB7CiAgICAiMSI6IHsKICAgICAgImV2ZW50cyI6IHt9LAogICAgICAibGlua3MiOiB7fSwKICAgICAgImFkZHJlc3MiOiAiMHg5OWMxNjU5MzA3YzBlMDY5ZDRhZDM2MDY2MjgzODAzZmNlZDM5ZTNlIiwKICAgICAgInVwZGF0ZWRfYXQiOiAxNTE1NzYyMTQyNDU4CiAgICB9CiAgfSwKICAic2NoZW1hX3ZlcnNpb24iOiAiMC4wLjUiLAogICJ1cGRhdGVkX2F0IjogMTUxNTc2MjE0MjQ1OAp9";
try {
  web3.personal.unlockAccount($$$account$$$, $$$password$$$);

  var certificateJson = atob(certificateJsonB64);
  var certificateProto = JSON.parse(certificateJson);
  var certificateProxy = web3.eth.contract(certificateProto.abi);
  var contract = certificateProxy.at($$$address$$$);

  var approxTxGas = 900000 + 21000; // sign + transfer(twice)
  var maxGasPrice = new BigNumber(web3.toWei(20, "gwei"));
  var approxTxPrice = maxGasPrice.times(approxTxGas); // average gas price
  var balance = new BigNumber(web3.eth.getBalance($$$account$$$));
  if( balance.lessThan(approxTxPrice) )
    throw "insufficient funds for gas";

  var _value = new BigNumber(web3.eth.getBalance($$$account$$$)).minus(approxTxPrice);

  // uint _id, uint _validate_hash, uint _birthday, uint8 _gender, uint _dt_sign, string _fullname
  var transactionHash = contract.Sign($$$id$$$, $$$validate_hash$$$, $$$birthday$$$, $$$gender$$$, new Date().getTime().toString(), $$$fullname$$$,
    {from:$$$account$$$, to:$$$address$$$, value:_value.toString(), gas:approxTxGas, gasPrice:maxGasPrice.toString()});

  web3.personal.lockAccount($$$account$$$);
  console.log(transactionHash);
}
catch(e) {
  console.log("EXCEPTION:");
  console.log(e);
};
